version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    
    steps:
      - checkout
      - run:
          name: install-deps
          command: npm install
      - run:
          name: test
          command: npm run test
